server:
  port: 8080
  ssl:
    key-store: classpath:safehouse.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: spring-https

jwt:
  secret: 'secretKeyForApzProjFAJFASLDKJFLSAKDJFASLDKJFASLDKJFAJFAKJF'
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/