server:
  port: 0

spring:
  application:
    name: device-service
  datasource:
    url: jdbc:postgresql://localhost:5434/device-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/